######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 30 15:08:33 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += combineimages.h
SOURCES += combineimages.cpp main.cpp
